-- =============================================================================
-- LostLink — PostgreSQL / Supabase Demo Catalog & Schema Seed Script
-- Compatible with PostgreSQL 13+ / Supabase
-- =============================================================================

-- 1. Ensure Tables Exist (if not already generated by Spring Boot JPA)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    department VARCHAR(255),
    staff_badge_number VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(31) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    location VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    image_url VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    reward VARCHAR(255),
    custody_desk VARCHAR(255),
    storage_bin VARCHAR(255),
    verification_question VARCHAR(255),
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS found_items (
    id BIGINT PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
    storage_location VARCHAR(255),
    handoff_instructions VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS lost_items (
    id BIGINT PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
    reward VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claimant_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    proof_description VARCHAR(1000),
    status VARCHAR(255) NOT NULL,
    handover_code VARCHAR(6),
    handover_pin VARCHAR(6),
    is_handover_verified BOOLEAN DEFAULT FALSE,
    verification_answer TEXT,
    proof_image_url VARCHAR(255),
    failed_pin_attempts INTEGER DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    resolved_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS claim_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    claimant_id BIGINT,
    sender_name VARCHAR(255),
    content VARCHAR(1000) NOT NULL,
    image_url VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message VARCHAR(255) NOT NULL,
    related_item_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- =============================================================================
-- 2. Seed Default Campus Demo Users
-- Passwords:
-- Admin: Admin@123
-- Students: Password@123
-- =============================================================================
INSERT INTO users (id, email, name, password, phone_number, role)
VALUES
(1, 'admin@lostfound.edu', 'Campus Admin', '$2a$10$GhuuHZRJsFMuYCP.xueUrej4.RlTosiOWrBFYiecfS7UjOSmct/KS', '555-0199', 'ROLE_ADMIN'),
(2, 'rohan@student.edu', 'Rohan Sharma', '$2a$10$h6uHROckPRi3lfM6gmAM5ehRh.OWEe8izMHQW8v.v/b/jwIKqOmdK', '555-0101', 'ROLE_USER'),
(3, 'abinav@lostfound.edu', 'Abinav Sabu', '$2a$10$py4bRwBozd7ZObASlPyN7ObUv9BFnVa7F59o/Fg0mQ/0.Ki5g.Spi', '555-0102', 'ROLE_USER'),
(4, 'david@student.edu', 'David Miller', '$2a$10$lW4k61oAYosoaXhMheZomek2QsulpCqRX.mwLDXlfPLIWk10qzEKC', '555-0103', 'ROLE_USER'),
(5, 'sneha@student.edu', 'Sneha Patel', '$2a$10$/Th.2ousSG./mQ4yL0EGm.fbKn1aR7pX0q/5R6s0a6MtEafwpr5nC', '555-0104', 'ROLE_USER')
ON CONFLICT (id) DO NOTHING;

INSERT INTO admins (id, department, staff_badge_number)
VALUES (1, 'Campus Security & Facilities', 'ADMIN-001')
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 3. Seed 12 Curated Demo Items & Polymorphic Tables
-- =============================================================================
INSERT INTO items (id, item_type, category, custody_desk, date, description, image_url, latitude, location, longitude, reward, status, storage_bin, title, verification_question, user_id)
VALUES
(1, 'LOST', 'ELECTRONICS', NULL, CURRENT_DATE - INTERVAL '3 days', 'Apple iPhone 15 Pro 128GB in Natural Titanium with clear MagSafe case and small hairline scratch on upper bezel.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8001.jpg', 37.7749, 'Student Union - 2nd Floor Lounge', -122.4194, '$50 Reward', 'LOST', NULL, 'Apple iPhone 15 Pro (Natural Titanium)', 'What is the lock screen wallpaper picture?', 2),
(2, 'FOUND', 'ELECTRONICS', 'Library Central Circulation Desk', CURRENT_DATE - INTERVAL '2 days', 'Space Gray 13-inch MacBook Air M2 found on silent study desk 14. Kept in navy neoprene protective sleeve.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8002.jpg', 37.7752, 'Main Library - 2nd Floor Study Area', -122.4189, NULL, 'FOUND', 'BIN-ELEC-402', 'Apple MacBook Air M2 (Space Gray)', 'What color protective skin or stickers are on the keyboard deck?', 3),
(3, 'FOUND', 'WALLETS_CARDS', 'Sports Complex Welcome Desk', CURRENT_DATE - INTERVAL '4 days', 'Genuine navy blue leather bi-fold wallet by Tommy Hilfiger. Contains student identification and transit card.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8003.jpg', 37.7740, 'Indoor Sports Complex - Court 2', -122.4201, NULL, 'CLAIMED', 'BIN-WALLET-104', 'Navy Blue Leather Bi-Fold Wallet', 'What is the name printed on the transit smartcard inside?', 3),
(4, 'LOST', 'CLOTHING', NULL, CURRENT_DATE - INTERVAL '3 days', 'Black 28L North Face Borealis backpack with reflective bungee cords and side mesh water bottle pockets.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8004.jpg', 37.7758, 'Science Block B - Lecture Hall 101', -122.4175, '$30 Reward', 'LOST', NULL, 'The North Face Borealis Backpack (Black)', 'What textbook title was inside the main zipper pocket?', 4),
(5, 'FOUND', 'KEYS', 'Campus Security Office (Gate 1)', CURRENT_DATE - INTERVAL '2 days', 'Heavy duty matte black climbing carabiner holding 2 brass Yale dorm keys, 1 Kryptonite U-lock key, and red tag.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8005.jpg', 37.7761, 'Science Quad - Bicycle Racks', -122.4178, NULL, 'FOUND', 'BIN-KEYS-105', 'Set of Dorm & Bike Keys on Black Carabiner', 'What text or logo is engraved on the red tag?', 3),
(6, 'FOUND', 'ELECTRONICS', 'Recreation Center Front Desk', CURRENT_DATE - INTERVAL '6 days', '45mm Apple Watch Series 9 GPS in Midnight aluminum casing with black sport band. Turned in after evening gym workout.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8006.jpg', 37.7738, 'Campus Recreation Center - Weight Room', -122.4190, NULL, 'REUNITED', 'BIN-ELEC-310', 'Apple Watch Series 9 (Midnight Aluminum 45mm)', 'What Bluetooth device name is displayed under Settings?', 5),
(7, 'FOUND', 'ELECTRONICS', 'Dining Hall Info Booth', CURRENT_DATE - INTERVAL '2 days', 'Silver/platinum over-ear Sony WH-1000XM5 noise cancelling headphones in matching zip carry case.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8007.jpg', 37.7745, 'Dining Hall - South Booths', -122.4182, NULL, 'FOUND', 'BIN-AUDIO-118', 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones', 'What auxiliary cord color is stored inside the case zipper pocket?', 3),
(8, 'LOST', 'OTHER', NULL, CURRENT_DATE - INTERVAL '3 days', '32oz wide-mouth olive green Hydro Flask with flex cap, decorated with national parks stickers and NASA badge.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8008.jpg', 37.7750, 'University Lawn - Amphitheater', -122.4168, '$15 Reward', 'LOST', NULL, 'Stainless Steel Hydro Flask (Olive Green 32oz)', 'Name two stickers placed beneath the logo?', 5),
(9, 'FOUND', 'ELECTRONICS', 'Math Department Office (Room 101)', CURRENT_DATE - INTERVAL '2 days', 'Dark blue TI-84 Plus CE graphing calculator with slide cover. Found on desk in calculus recitation classroom.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8009.jpg', 37.7765, 'Mathematics Hall - Room 204', -122.4185, NULL, 'FOUND', 'BIN-ELEC-219', 'Texas Instruments TI-84 Plus CE Graphing Calculator', 'What initials are etched inside the slide cover?', 3),
(10, 'FOUND', 'WALLETS_CARDS', 'Engineering Student Helpdesk', CURRENT_DATE - INTERVAL '4 days', 'Official University RFID campus access smartcard on blue lanyard with student barcode on reverse.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8010.jpg', 37.7755, 'Engineering Complex - Atrium', -122.4170, NULL, 'CLAIMED', 'BIN-CARD-055', 'Campus Student ID & Access Smartcard', 'What is the last 4 digits of the card barcode?', 4),
(11, 'LOST', 'OTHER', NULL, CURRENT_DATE - INTERVAL '3 days', 'Navy blue compact folding umbrella with automatic open/close button and wooden curved handle grip.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8011.jpg', 37.7742, 'Humanities Building - 1st Floor Lobby', -122.4179, '$10 Reward', 'LOST', NULL, 'Compact Windproof Travel Umbrella (Navy Blue)', 'What brand initials are engraved on the wooden handle base?', 2),
(12, 'FOUND', 'OTHER', 'Campus Police & Parking Office', CURRENT_DATE - INTERVAL '7 days', 'Matte black Trek FX 2 Disc commuter bike with rear luggage rack and mounted front LED headlight.', '/uploads/d1b7a240-6f81-423c-91d1-61019a6d8012.jpg', 37.7748, 'Student Center - West Bike Pavilion', -122.4210, NULL, 'REUNITED', 'BIN-BIKE-004', 'Trek FX 2 Disc City Commuter Bicycle (Matte Black)', 'What is the bicycle frame serial number stamped beneath bottom bracket?', 2)
ON CONFLICT (id) DO NOTHING;

INSERT INTO lost_items (id, reward)
VALUES
(1, '$50 Reward'),
(4, '$30 Reward'),
(8, '$15 Reward'),
(11, '$10 Reward')
ON CONFLICT (id) DO NOTHING;

INSERT INTO found_items (id, storage_location, handoff_instructions)
VALUES
(2, 'Shelf 4B', 'Claim at Central Desk with matching serial number'),
(3, 'Safe 1', 'Verify ID at Welcome Desk'),
(5, 'Key Lockbox 2', 'Claim at Security Gate 1 with ID'),
(6, 'Locker 3', 'Pair to your phone at front desk'),
(7, 'Locker A', 'Turn in at Info Booth'),
(9, 'Cabinet 2', 'Claim at Math Dept office with student ID'),
(10, 'Drawer 1', 'Claim with another photo ID'),
(12, 'Bike Shed A', 'Show lock key or purchase receipt')
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 4. Seed Claims
-- =============================================================================
INSERT INTO claims (id, created_at, failed_pin_attempts, handover_code, handover_pin, is_handover_verified, proof_description, proof_image_url, resolved_at, status, verification_answer, claimant_id, item_id)
VALUES
(1, CURRENT_TIMESTAMP - INTERVAL '4 days', 0, '582914', '582914', FALSE, 'Wallet has my student ID card (Rohan Sharma) and blue transit pass in left slot.', NULL, NULL, 'APPROVED', 'Student ID inside', 2, 3),
(2, CURRENT_TIMESTAMP - INTERVAL '6 days', 0, '491028', '491028', TRUE, 'Paired to my iPhone named ''David iPhone'' with serial ending in 9F21.', NULL, CURRENT_TIMESTAMP - INTERVAL '5 days', 'APPROVED', 'David iPhone', 4, 6),
(3, CURRENT_TIMESTAMP - INTERVAL '4 days', 0, '739105', '739105', FALSE, 'Card displays student ID number 2024-ENG-0881 and name Sneha Patel.', NULL, NULL, 'APPROVED', 'Student ID number 2024-ENG-0881', 5, 10),
(4, CURRENT_TIMESTAMP - INTERVAL '7 days', 0, '615842', '615842', TRUE, 'Trek FX 2 frame number WTU304C0918T with red Bell water bottle cage.', NULL, CURRENT_TIMESTAMP - INTERVAL '6 days', 'APPROVED', 'WTU304C0918T', 3, 12)
ON CONFLICT (id) DO NOTHING;

-- Synchronize Identity Sequences
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1) + 1, false) FROM users;
SELECT setval(pg_get_serial_sequence('items', 'id'), COALESCE(MAX(id), 1) + 1, false) FROM items;
SELECT setval(pg_get_serial_sequence('claims', 'id'), COALESCE(MAX(id), 1) + 1, false) FROM claims;
